// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 侧边栏 “helpSidebar” 对应 docs/help 文件夹
  helpSidebar: [
    {
      type: 'autogenerated',
      dirName: 'help',   // 只扫描 help 目录
    },
  ],

  // 侧边栏 “articleSidebar” 对应 docs/article 文件夹
  articleSidebar: [
    {
      type: 'autogenerated',
      dirName: 'article',
    },
  ],
};

export default sidebars;
